
# -- Include the TF module to create the Storage Account
enabled: true

# -- Terraform Remote State configuration
state:
  # -- The Name of the Resource Group in which the Storage Account exists
  resource_group_name: ""
  # -- The Name of the Storage Account
  storage_account_name: ""
  # -- The Name of the Storage Container within the Storage Account
  container_name: ""
