{{ if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "adls-gen2.fullname" . }}
  labels:
    {{- include "adls-gen2.labels" . | nindent 4 }}
data:
  {{- tpl (.Files.Glob "files/*.tf").AsConfig . | nindent 2 }}
{{ end }}
